### ISSUE TITLE
mpromise Deperacation

### ISSUE THREAD

**Issue by sadboyzvone** [marchah/mongoose-increment#6]
(node:12431) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

Do you know how I should fix this?

**Comment by marchah** [comment]
In your mongoose conf file, where you connect to your database for example add that:

```javascript
const Promise = require('bluebird');
const mongoose = require('mongoose');

mongoose.Promise = Promise;
```
